
import 'package:flutter/material.dart';
import 'EquipmentItem.dart';

final DUMMY_EQUIPMENT = [

  EquipmentItem(
    id: 'e1', 
    categories: ['c1'], 
    type: 'Laptop', 
    title: 'Laptop', 
    pricePerHour: 2.0,
    pricePerWeek: 25.0,
    pricePerMonth: 80.0,
    pricePerYear: 800.0,
    condition: Condition.good, 
    rentalType: RentalType.hourly, 
    icon: Icons.laptop,
    description: 'A good laptop for work and study',
    releaseYear: 2023,
    status: ProductStatus.available,
  ),

  EquipmentItem(
    id: 'e2', 
    categories: ['c1'], 
    type: 'Smartphone', 
    title: 'Smartphone', 
    pricePerHour: 1.0,
    pricePerWeek: 15.0,
    pricePerMonth: 50.0,
    pricePerYear: 500.0,
    condition: Condition.newCondition, 
    rentalType: RentalType.hourly, 
    icon: Icons.phone_android,
    description: 'Latest model smartphone',
    releaseYear: 2024,
    status: ProductStatus.rented,
  ),

  EquipmentItem(
    id: 'e3', 
    categories: ['c1'], 
    type: 'Headphones', 
    title: 'Headphones', 
    pricePerHour: 0.5,
    pricePerWeek: 8.0,
    pricePerMonth: 25.0,
    pricePerYear: 250.0,
    condition: Condition.good, 
    rentalType: RentalType.hourly, 
    icon: Icons.headphones,
    description: 'Noise-cancelling headphones',
    releaseYear: 2023,
    status: ProductStatus.available,
  ),

  EquipmentItem(
    id: 'e4', 
    categories: ['c1'], 
    type: 'Tablet', 
    title: 'Tablet', 
    pricePerHour: 1.2,
    pricePerWeek: 20.0,
    pricePerMonth: 60.0,
    pricePerYear: 600.0,
    condition: Condition.good, 
    rentalType: RentalType.weekly, 
    icon: Icons.tablet,
    description: 'Lightweight tablet for study or work',
    releaseYear: 2023,
    status: ProductStatus.rented,
  ),

  EquipmentItem(
    id: 'e5', 
    categories: ['c1'], 
    type: 'Smartwatch', 
    title: 'Smartwatch', 
    pricePerHour: 0.7,
    pricePerWeek: 12.0,
    pricePerMonth: 35.0,
    pricePerYear: 350.0,
    condition: Condition.newCondition, 
    rentalType: RentalType.hourly, 
    icon: Icons.watch,
    description: 'Smartwatch with fitness tracking',
    releaseYear: 2024,
    status: ProductStatus.available,
  ),

  EquipmentItem(
    id: 'e6', 
    categories: ['c2'], 
    type: 'Gaming PC', 
    title: 'Gaming PC', 
    pricePerHour: 3.0,
    pricePerWeek: 50.0,
    pricePerMonth: 150.0,
    pricePerYear: 1500.0,
    condition: Condition.newCondition, 
    rentalType: RentalType.hourly, 
    icon: Icons.desktop_windows,
    description: 'High performance gaming PC',
    releaseYear: 2024,
    status: ProductStatus.rented,
  ),

  EquipmentItem(
    id: 'e7', 
    categories: ['c2'], 
    type: 'Printer', 
    title: 'Printer', 
    pricePerHour: 0.8,
    pricePerWeek: 15.0,
    pricePerMonth: 45.0,
    pricePerYear: 450.0,
    condition: Condition.good, 
    rentalType: RentalType.weekly, 
    icon: Icons.print,
    description: 'Color printer for home or office',
    releaseYear: 2023,
    status: ProductStatus.available,
  ),
  EquipmentItem(
    id: 'e11', 
    categories: ['c3'], 
    type: 'Bicycle', 
    title: 'Bicycle', 
    pricePerHour: 1.0,
    pricePerWeek: 18.0,
    pricePerMonth: 55.0,
    pricePerYear: 550.0,
    condition: Condition.good, 
    rentalType: RentalType.hourly, 
    icon: Icons.directions_bike,
    description: 'Mountain bike for outdoor adventures',
    releaseYear: 2022,
    status: ProductStatus.available,
  ),

  EquipmentItem(
    id: 'e12', 
    categories: ['c3'], 
    type: 'Tent', 
    title: 'Tent', 
    pricePerHour: 1.5,
    pricePerWeek: 25.0,
    pricePerMonth: 70.0,
    pricePerYear: 700.0,
    condition: Condition.newCondition, 
    rentalType: RentalType.weekly, 
    icon: Icons.home_work,
    description: 'Camping tent for 2 people',
    releaseYear: 2024,
    status: ProductStatus.rented,
  ),

  
  EquipmentItem(
    id: 'e16', 
    categories: ['c4'], 
    type: 'Hammer', 
    title: 'Hammer', 
    pricePerHour: 0.3,
    pricePerWeek: 5.0,
    pricePerMonth: 15.0,
    pricePerYear: 150.0,
    condition: Condition.good, 
    rentalType: RentalType.hourly, 
    icon: Icons.build,
    description: 'Durable hammer for construction work',
    releaseYear: 2023,
    status: ProductStatus.available,
  ),

  EquipmentItem(
    id: 'e17', 
    categories: ['c4'], 
    type: 'Drill', 
    title: 'Drill', 
    pricePerHour: 1.0,
    pricePerWeek: 18.0,
    pricePerMonth: 50.0,
    pricePerYear: 500.0,
    condition: Condition.newCondition, 
    rentalType: RentalType.hourly, 
    icon: Icons.construction,
    description: 'Electric drill with multiple bits',
    releaseYear: 2024,
    status: ProductStatus.rented,
  ),

  EquipmentItem(
    id: 'e21', 
    categories: ['c5'], 
    type: 'Lawn Mower', 
    title: 'Lawn Mower', 
    pricePerHour: 2.5,
    pricePerWeek: 40.0,
    pricePerMonth: 120.0,
    pricePerYear: 1200.0,
    condition: Condition.good, 
    rentalType: RentalType.weekly, 
    icon: Icons.grass,
    description: 'Electric lawn mower for garden',
    releaseYear: 2023,
    status: ProductStatus.available,
  ),

  EquipmentItem(
    id: 'e26', 
    categories: ['c6'], 
    type: 'Jacket', 
    title: 'Jacket', 
    pricePerHour: 0.6,
    pricePerWeek: 10.0,
    pricePerMonth: 30.0,
    pricePerYear: 300.0,
    condition: Condition.newCondition, 
    rentalType: RentalType.hourly, 
    icon: Icons.checkroom,
    description: 'Warm jacket for winter',
    releaseYear: 2024,
    status: ProductStatus.rented,
  ),
];
